MetaPhase-Consulting/State-TalentMAP-API

talentmap_api/bidding/models.py, talentmap_api/bidding/serializers/serializers.py, talentmap_api/bidding/tests/test_bid.py
Adds a can_delete property to bids so front end does not need to calculate this each time.
=> feature: add can_delete property to bid

requirements.txt
We received a vulnerability disclosure from GitHub indicating we need to upgrade.  From what I see we don't seem to require this library anymore (requirements changed).
=> Security fix - PyYAML

talentmap_api/integrations/models.py
This removes the warning about timezones when running the data sync
=> fix: remove timezone warning when running sync job

talentmap_api/bidding/tests/test_bid.py, talentmap_api/bidding/tests/test_bidlist.py, talentmap_api/bidding/views/bid.py, talentmap_api/bidding/views/bidlist.py, talentmap_api/common/management/commands/create_base_permissions.py, talentmap_api/user_profile/management/commands/create_seeded_users.py
TM-403 - adds the bidder role and restricts access to some of the end points around bidding to this role.
The bidder role needs to be assigned to any user that would want to perform these actions
=> feature: bidder role restricting access to bidder actions

talentmap_api/position/serializers.py, talentmap_api/user_profile/urls/client.py, talentmap_api/user_profile/views/client.py
Updates to API that were needed for the public profile page:
- Add new endpoint for clients by assignment (/client/:id/assignments)
- Include `id` and `languages` in the assignment's `position` object
=> Client assignments endpoint

talentmap_api/integrations/synchronization_helpers.py
The web services team is updating their services to allow filtering by `last_updated_date`.  This update requires changes the version number.
=> Update version number

talentmap_api/position/serializers.py
Adds org info to the position data payload for domestic positions. Depending on whether or not the position is in DC changes what info comes down.
=> feature: add org info for domestic positions. TM-442

talentmap_api/position/filters.py, talentmap_api/position/tests/test_position_endpoints.py
Adds a new filter language_code that accepts language codes as well as a special value `NONE` that uses the language__isnull filter.
`language_codes=QB,DE,NONE` = all positions with language requirements with code QB and DE as well as positions that have no language requirement.
=> feature: allow for language and no language requirement filters to be used together. TM-401

talentmap_api/position/filters.py
solves issue with a position with multiple languages showing up twice
=> fix: use distinct to only return one of each position. TM-401

talentmap_api/position/serializers.py, talentmap_api/user_profile/serializers.py
Adds client's assignment history to response data to support new feature in the bidder portfolio.
=> Add assignment history to client response

deploy.sh, talentmap_api/fsbid/services.py, talentmap_api/fsbid/tests/test_fsbid_projected_vacancies.py, talentmap_api/fsbid/urls/projected_vacancies.py, talentmap_api/fsbid/views/projected_vacancies.py, talentmap_api/urls.py
Basic outline for TM-643. Just gets all the projected vacancies from the mock api and returns the list.
Builds on feature/fsbid-get-bids branch. See #57.
=> feature: basic projected vacancies get end point

talentmap_api/user_profile/views/client.py
Ordering by anything fixes the pagination duplicates. Talked with Mike and ordering by ID makes the most sense.
=> adding ordering to client queryset to address pagination duplicates

talentmap_api/position/serializers.py
For some reason this was not included in the PositionList serializer, resulting in OBC links not being displayed on the Compare page.
=> Add obc_id to PositionList serializer

talentmap_api/bidding/models.py, talentmap_api/position/serializers.py
only include active cycles in cycles considered when updating the latest_bidding_cycle field on a position. Also, added a function to run this same situation on all positions in the cycle when the status of the cycle changes.
=> update latest_bid_cycle to only include active cycles

talentmap_api/bidding/views/cycleposition.py
Resolves part of discrepancy between FSBid and TalentMAP count
=> Filter out cyclepositions that have a null posted_date

talentmap_api/fsbid/services/common.py, talentmap_api/fsbid/services/projected_vacancies.py
rather than send comma separated values for a param, send params as multiple keys in query string. 
so 
`fv_request_params.seq_nums=1,2,3` 
becomes `fv_request_params.seq_nums=1&fv_request_params.seq_nums=2&fv_request_params.seq_nums=3`
=> fix: allow multiple filter values to be sent to fsbid as the same param. Addresses TM-1203 TM-1204 TM-1206

talentmap_api/settings.py
Click on the Authorize button in the header of the Swagger site and enter something into the jwt box. This will send that header with requests so all the endpoints that require JWT can be tested via swagger
=> chore: allow for jwt to be set for swagger calls via authorize

talentmap_api/fsbid/views/available_positions.py, talentmap_api/fsbid/views/projected_vacancies.py
adds id comma separated filter capabilities used in the comparison. needed for https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/433
use the following urls...
`/api/v1/fsbid/availablePositions?id=1,2`
`/api/v1/fsbid/projectedVacancies?id=1,2`
swagger also has id field that accepts comma separated string for multiple values
=> feature: capture ids as a filter used in comparison

talentmap_api/fsbid/filters.py
fixes the saved searches for projected vacancies and comments out the line breaking the syncs. they were both in the same file so i just did them.
=> fix: comment out code that was breaking sync

talentmap_api/fsbid/filters.py
fixed issue where the count returning nothing was causing downstream calls to break
=> fix: return a value so things dont break

Dockerfile
This should prevent requirements from getting reinstalled between every `docker-compose build`.
=> Cache pip requirements between docker-compose builds

talentmap_api/fsbid/services/common.py
adds posted date as a valid sort option
=> fix: allow sorting on posted_date. TM-1337

docker-compose.local-fsbid.yml, docker-compose.override.yml
turns off the debugging of the sql in the mock by default
=> chore: add debug env value

docker-compose.yml
keeps the database around between builds and other activities
=> chore: use a correct volumne for mock db

talentmap_api/fsbid/services/available_positions.py
`cp_id`s are getting mapped in the format of `10901.0` causing them not to match a similar position id in the format of `10901`. This converts the source id to a float to ensure that the position id is filtered out from the similar results. This also fixes the fact that when the requested id is filtered out, we are missing out on one additional result in the request.
We should look into ensuring that ids aren't coming through as floats, as I've also seen that in response payloads.
=> Fix the requested position id being included in similar position results

talentmap_api/fsbid/services/client.py, talentmap_api/fsbid/urls/client.py, talentmap_api/fsbid/views/client.py
The basic flow is:
- Perform an AP search with the user's skills and grade
- If the count of this search is less than 5, perform a search with the next grade "up"
- If the new search has less than 100 results, recommend it
- If the new search has more than 100 results, only recommend it if the first search had 0 results
- If both searches returned the same number of results, recommend the first
=> Add service for CDOs to get search suggestions for a client

talentmap_api/fsbid/services/bid.py
Pretty sure I was using Javascript-style string interpolation when I made the original fix :dizzy_face: i.e. `${...}` vs `{...}`
Also adds the ad_id to the /remove endpoint
=> Fix string interpolation and add ad_id to /remove endpoint

talentmap_api/fsbid/services/bid.py
FSBid returns these as floats, so the decimals breaks some front-end URL anchoring functionality.
=> Convert cp_id to a string

talentmap_api/fsbid/services/cdo.py, talentmap_api/fsbid/services/client.py, talentmap_api/fsbid/urls/cdo.py, talentmap_api/fsbid/views/cdo.py, talentmap_api/user_profile/models.py, talentmap_api/user_profile/serializers.py
This is not fully functioning since our mock is not updated, but the /Agents endpoint should be able to accept a `perdet_seq_num` query parameter, so that the agent of a client with a given perdet can be retrieved. This performs that lookup and adds the response to the UserProfile and Client responses.
=> Return the CDO of the user from FSBid

talentmap_api/fsbid/services/client.py, talentmap_api/fsbid/services/common.py, talentmap_api/fsbid/views/client.py
sort on grade or skill or send both using the python - syntax for direction. The implementation of the field names may change based on FSBid but none of the computers have DevNet so i can't check it. The mock currently accepts params grade and skill for testing purposes
=> TM-1566 - feature: add sorting for the cdo clients endpoint

talentmap_api/available_positions/views/available_position.py
Add parameters when exporting favorites to `?exclude_available` positions and/or `?exclude_projected` vacancies.
=> Add parameters for exporting favorites

talentmap_api/fsbid/services/common.py
Add new ordering mappings for /CDOClients. Causes uncaught error with mock
=> Additional ordering mapping

talentmap_api/fsbid/services/client.py
A bit complex because of handling objects vs arrays, but the purpose was to get a common object type to pass into `fsbid_assignments_to_tmap`
Use with https://github.com/MetaPhase-Consulting/mock-fsbid/pull/50
=> Map assignments/current_assignment from CDOClients

talentmap_api/available_positions/urls/available_positions.py, talentmap_api/available_positions/views/available_position.py, talentmap_api/projected_vacancies/urls/projected_vacancies.py, talentmap_api/projected_vacancies/views/projected_vacancy.py
Return a simple list of the IDs of the user's favorites (`["1", "5", "101", ...]`). Will be used with a front-end PR to improve the the load time after adding/removing a favorite. This PR can be merged before that.
=> Add routes to fetch only the IDs of the user's favorite positions

docker-compose-api-only.yml
For running the API and mock separately.
`docker-compose -f docker-compose-api-only.yml up`
=> Custom docker compose for running API and mock separately

requirements.txt
Bumps this requirement to get rid of a build error in local docker setup
=> Bump MarkupSafe requirement to avoid build error

talentmap_api/common/management/commands/create_base_permissions.py, talentmap_api/fsbid/services/employee.py
Adds permission mapping for bureau user.
Be sure to run `manage.py create_base_permissions` as well to get the local permission created.
=> Add bureau_user permission

talentmap_api/fsbid/services/client.py, talentmap_api/fsbid/services/common.py, talentmap_api/settings.py
Adds external URLs to the employee profile URLs (one internal network, one external network), as we do not want to proxy the PDF response through the TalentMAP API. Front-end to come.
=> Add internal/external employee profile URLs

talentmap_api/fsbid/services/employee.py, talentmap_api/fsbid/urls/employee.py, talentmap_api/fsbid/views/employee.py
- This creates the service and url for retrieving the authorized bureau codes for a bureau user
- Payload is simply an array of codes(ids) and names(descriptions) for the bureaus to properly display the options available to filter in bureau position management on the FE.
=> Add bureau_codes mapping for bureau user permissions

talentmap_api/fsbid/services/available_positions.py, talentmap_api/fsbid/services/bureau.py, talentmap_api/fsbid/services/projected_vacancies.py
Pass bureau filters as-is and do not do any internal mapping. Resolves functional bureau filtering issue.
=> Don't use internal bureau mapping

talentmap_api/fsbid/services/available_positions.py
Increase the limit to increase the chance that 3 positions will show up after filter. [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/1114)
=> increasing similar positions return limit

talentmap_api/fsbid/services/common.py
Need to check fsbid to confirm the syntax of these new sorts. Its difficult to check b/c I need to add bids to a cp_id in swagger to check the returned bidders sorting correctly. I will confirm in the comments when ready to merge. Wait till @mjoyce91 merges bureau positions endpoint changes to test locally
Dual Merge: https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/1123
=> Add new sorts and mappings for bidders TM-1899

talentmap_api/fsbid/services/bureau.py
Dual Merge: https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/1190
- Adds bureau short desc so that we can show the acronym on the results card instead of the lengthy full name
=> Add short desc for bureau to put on bureau search card

talentmap_api/fsbid/services/bureau.py, talentmap_api/fsbid/services/common.py
- Use /availablePositions instead of /cyclePositions
- Don't return empty values (like `['']`) to web services, as they break it
=> Release fixes

.circleci/config.yml
Might fix a possible conflict between python versions on CircleCI for building dependencies vs the deployed environment.
=> Use 3.6.8 for building dependencies

talentmap_api/fsbid/views/bureau.py
Adds new properties to a single bureau position that indicate whether the requesting user have bureau or post permissions.
=> Add bureau/post permissions to bureau position payload

talentmap_api/fsbid/services/client.py
adding gal email to user_info; leaving other email alone in case we use it in other places
Dual Merge: [FE](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/1376)
=> adding gal email to user_info

talentmap_api/fsbid/services/bid.py, talentmap_api/fsbid/services/client.py, talentmap_api/fsbid/views/employee.py
- This is causing an issue with the client profiles page when someone has a pert_external_id that includes letters
Test:
=> Fixing redundant data transform to str from int

requirements.txt, talentmap_api/settings.py
In response to https://github.com/MetaPhase-Consulting/State-TalentMAP-API/pull/513
Use minimal safe version to avoid breaking changes
=> Upgrade pysaml2 from 4.4.0 to 4.6.0

talentmap_api/fsbid/services/employee.py
`developer` jwt role now maps to `['fsofficer', 'CDO', 'Bureau', 'AO']`
=> Mapping for the developer role

SETUP.md, docker-compose-api-only.yml, docker-compose.yml
To test:
- do something that will trigger an email notification (registering a handshake is the easiest)
- navigate to http://localhost:1080 and ensure the email notification appears
Note: emails will not persist between container ups/downs
=> Add fake smtp server for local testing

talentmap_api/common/common_helpers.py
Send emails alongside any internal handshake notifications. All that was needed was `send_email(message, message, [owner.user.email])` but I included some other tweaks including:
- `bureau` vs `bureau_user` variable naming
- wrap email action in a try/except so that any issues with sending the email don't cause the entire request to fail
=> Send emails for handshake notifications; few other tweaks

talentmap_api/bidding/views/bidhandshake.py, talentmap_api/common/common_helpers.py
When a bidder accepts or declines a handshake, an email notification is sent to their CDO. This requires a network request to determine who their CDO is and what their email is.
=> Email CDO when bidder accepts/declines a handshake

talentmap_api/fsbid/services/client.py
This mapping isn't completely compatible with available bidders data, but this update at least gets the bureau code to return so that we can use it to populate the Edit Bidder modal.
=> Return bureau code when mapped by available bidders function

talentmap_api/fsbid/services/client.py
Fixes unhandled error when `bureau` is `None`
=> Bureau code undefined fix

talentmap_api/bidding/views/bidhandshake.py
Don't reset expiration UNTIL new offer on THIS handshake. The assumption is _EVERY_ valid HS has an expiration until it is overwritten -> we'll use that expiration_date to determine status icons, and info-only modal expiration time (historical). Otherwise we cannot show the expired icon after revoke or the past expiration time before re-offer (on currently revoked).
=> Maintain expire on Revoke status update for historical hs

talentmap_api/fsbid/services/available_positions.py, talentmap_api/fsbid/services/common.py
Bug: Tandem hierarchal sort isn't working properly (Tandem 1 and Tandem 2 results should be grouped logically specified below)
- This should properly map the fixed sorts
1. CommuterPosts
2. Location (city)
3. (location code for duplication locations above) 
4. Tandem
5. Specified User Sort (last)
=> Add dict for new sorts for tandem TM-2278

talentmap_api/bidding/services/bidhandshake.py, talentmap_api/fsbid/services/bid.py
Prevents revoked handshakes from appearing on the bidder/CDO bid list. Previously, if a bidder accepted a handshake but then it was revoked, the HS overlay would still appear in the UI. This PR resolves that issue.
=> Exclude Revoked HS from bidder bid list

talentmap_api/bidding/views/bidhandshake.py, talentmap_api/fsbid/services/bid.py
Previously: bidder could only accept a handshake if they did not have any other accepted handshakes within any active bid cycle
With this PR: bidder can only accept one handshake within a bid cycle, regardless of whether they've accepted a handshake in another active cycle
=> Update so that bidder can only accept one handshake per bid cycle

talentmap_api/fsbid/services/available_positions.py
The following are invalid body parameters with the new POST request:
`[null]`
`[]`
This PR ensures that order_by will not be sent like this.
=> Filter out null'd/empty arrays from POST

talentmap_api/fsbid/services/client.py
- ~~Still trying to correctly mock out the scenario, but~~ this should prevent tmap from mapping the language object if there's not title for the language
- Modified custom description in lang object to be used on modal to account for missing test scores
=> null-check-for-mapping TM-2283

talentmap_api/fsbid/services/client.py
The scores should always be returned as strings anyways but this is a safety check and accounts for white space
=> Add fallback to make sure empty scores come back as '--'

talentmap_api/fsbid/services/bid.py
This is needed when we need to do cp_id checks inside position_info, but position_info isn't returned because the bid isn't returned by ap_services. https://github.com/MetaPhase-Consulting/State-TalentMAP-API/pull/598 should make that irrelevant (?) but still wanted to fix this.
=> Force return of ID in position_info

talentmap_api/available_positions/urls/available_positions.py, talentmap_api/fsbid/services/agenda.py, talentmap_api/fsbid/services/available_positions.py, talentmap_api/fsbid/services/bureau.py, talentmap_api/fsbid/services/common.py, talentmap_api/fsbid/services/positions.py, talentmap_api/fsbid/services/projected_vacancies.py, talentmap_api/fsbid/views/agenda.py
jumped between dev and this branch to confirm urls and their payloads were identical
=> refactoring get_individual (includes AI Export fix)

talentmap_api/fsbid/services/agenda_employees.py
If you do an employee agenda search by 'a012345', it should return the user with id 'A012345'. The ID specific search should be case-insensitive. 
Tested Successfully in Dev1
=> Employee Agenda Search - Case Insensitive Free Text Search for Employee ID TM-2803

talentmap_api/fsbid/services/common.py
[FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2170)
To-do:
**Testing Checklist**
When the HS on the position is registered with the current bidder. Expected result in the export should be:
**status is case sensitive**
BE status: Export Value
When the position **does** have the HS indicator, but the HS is with another bidder. Expected result in the export should be:
**status is case sensitive**
BE status: Export Value
When the position **does not** have the HS indicator. Expected result in the export should be:
**status is case sensitive**
BE status: Export Value
=> bid tracker export clean up TM-3021

talentmap_api/fsbid/services/client.py
The Bureau dropdown option is showing as `None listed` in DEV1 and upper envs. 
To-do
**Note: Mock is not setup for this change yet. Results will show `None listed` in Local/AWS, however this should work properly in DEV1 and beyond.
The code below is already working in DEV1 and we only want the `short_desc` now for the `bureau_code` key
`"bureau": f"({pos.get('pos_bureau_short_desc', None)}) {pos.get('pos_bureau_long_desc', None)}",`**
**_I have verified that the data is appearing properly in DEV1 Swagger as well_**
=> fix abl bureau dropdown data TM-3084

talentmap_api/fsbid/services/common.py
=> op/pv tandem position number sort TM-3050

talentmap_api/common/common_helpers.py, talentmap_api/fsbid/services/projected_vacancies.py
In short, the date "0001-01-01T00:00:00" is being returned by WS and is throwing `ValueError: year 0 is out of range`.
The datetime function is looking/handling a lot of things. It is expecting certain ranges to be met (ie: only 12 months so you can't have `13-13-13` as a date even though the year and day are valid, etc.). With that being the case, this PR attempts to create a valid date out of a real but illogical date like the error we're receiving, but if it can't create the date at all it will show `Invalid date`. 
To-Do:
Edge cases to manually test in the PV services file (order can be rearranged ie: 01-0001-01/add any number ie: 01-23-1234):
- "0001-01-01T00:00:00"
- "001-01-01T00:00:00"
- "01-01-01T00:00:00"
- Whatever your ❤️ desirers
=> ted override error handling TM-3239

talentmap_api/bureau/services/available_bidders.py
Reverting changes from this [PR](https://github.com/MetaPhase-Consulting/State-TalentMAP-API/pull/719)
Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2361)
To-do:
**These changes are being undone per the request of the PO**
=> remove updated from exteranl abl

talentmap_api/fsbid/services/agenda_employees.py
ACs:
1. Verify filters being sent from backend to Web Services follows the same structure as below:
`tmperperfullname|CONTAINS|[first name/last name]`
`tmperpertexternalid|CONTAINS|[employee ID]`
2. Verify search works in DEV1
Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2433)
=> TM-3832: Adding support for split name search

talentmap_api/fsbid/services/agenda_employees.py
ACs:
1. Verify filters being sent from backend to Web Services follows the same structure as below:
`tmperperfullname|CONTAINS|[first name/last name]` with the last/first name being all caps
`tmperpertexternalid|EQ|[employee ID]` with the letters within the employee ID capitalized
=> TM-3832 Fix: Adding back .upper() functionality

talentmap_api/fsbid/services/agenda_employees.py
To verify on local, print `filters` in State-TalentMAP-API/talentmap_api/fsbid/services/agenda_employees.py `convert_agenda_employees_query`. Queries for filtered (active employees) should send back `tmperperscode|IN|A,L,P,S,U|` to the mock while unfiltered (active AND inactive employees) should not send that filter back. The `tmperperscode` filter is what differentiates active/inactive employees
Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2438)
=> TM-3849: Employee Agenda Search Inactive Employees Toggle

talentmap_api/fsbid/services/agenda_employees.py
ACs:
1. Verify API is now accurately sending new location fields in the following format: City, Country (Org)
Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2488)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/355)
=> TM-3905: adding new location fields to EP

talentmap_api/fsbid/services/agenda_employees.py
This was shockingly tricky - we should definitely make a function and keep it somewhere - where we can pass in all the name data from any endpoint and have it return cleanly. 
Might also need to update the mock - but not a requirement 
From Dev:
=> TM-4265, add suffix to agenda search name

talentmap_api/fsbid/services/common.py
Legacy Remarks
Show it and if editable it can be removed, but you can’t re-add it. If you can edit it then ` (legacy)` should let you know that you should remove/replace it. 
Glossary already filters out the legacy ones, so we should be good with preventing the adding of any new legacy ones.
=> denoting legacy remarks

talentmap_api/fsbid/services/client.py
ACs:
1. Verify client profile export is now showing the name as `Last, First Middle` instead of `First Middle Last`
=> TM-4323: changing order of names in export

talentmap_api/fsbid/services/agenda.py
Bugs Addressed:
- Empty languages array causes agendas call to fail
Dual Merge: 
=> TM-4990: Missing Emp Info Hotfix

talentmap_api/fsbid/services/agenda.py
OK - this was kind of tricky, and took me a little while to wrap my head around & think through. 
Decided to pass the "-" for not applicable fields from the backend, so the read-only fields of the frontend won't need any logic to decide how to render anything. 
The other option was to pass None from the API and then have the frontend parse and decide what to render - but i think that could make that code a little more messy than it needs to be.  Would just have to add the same logic to `AgendaItemLegsFormReadOnly` & `AgendaItemLegs` that's in `AgendaLeg` where the editing happens.  
Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2846)
[Ticket](https://metaphase.atlassian.net/browse/TM-5479)
=> TM-5479, none listed vs not applicable

talentmap_api/common/common_helpers.py, talentmap_api/fsbid/services/admin_projected_vacancies.py, talentmap_api/fsbid/urls/admin_projected_vacancies.py, talentmap_api/fsbid/views/admin_projected_vacancies.py
Updates:
- Fixed common service response function to allow for universal response JSONs
- Some back office responses contain different naming conventions for the RETURN_CODE and ERROR_DATA
- Added endpoint for editing PV (general)
- Added endpoint for editing PV language offsets
- Added endpoint for editing PV capsule description
- Added endpoint for getting PV language offsets
- Added endpoint for getting PV metadata
Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2861)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/437)
[TM-5389](https://metaphase.atlassian.net/browse/TM-5389)
[TM-5389]: https://metaphase.atlassian.net/browse/TM-5389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TM-5389] Projected Vacancy Integration (Edit)

talentmap_api/fsbid/services/assignment_cycles.py
Dual Merge: 
- [Frontend PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2898)
tiny fixes from testing -- the `create_new` cycle logic had the frontend passing in True/False and the backend parsing it... but now the update shares that same service/logic 
made it all more consistent - no more T/F just Y/N
=> 5412 tm edit cycle cleanup

talentmap_api/fsbid/services/admin_projected_vacancies.py
Updates:
- Include/Exclude
- Toggle changed to a checkbox
- This is editable only when no cards are in edit mode in order to keep modifications of exclude and status fields independent of one another
- When cards are in edit mode, the search disable banner now includes that adding to proposed cycle is unavailable until edits are saved or canceled
- Projected Vacancies are now filterable by organizations from fixing the request JSON
- Capsule Descriptions (Position Details) are now editable using the metadata now returned in the WS list endpoint
Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2927)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/459)
[TM-5710](https://metaphase.atlassian.net/browse/TM-5710)
[TM-5710]: …
=> [TM-5710] Projected Vacancy Integration Remediation

talentmap_api/common/management/commands/create_base_permissions.py, talentmap_api/fsbid/services/employee.py, talentmap_api/user_profile/management/commands/create_seeded_users.py
ACs:
1. New Menu Option for Panel Administrator (will reuse admin icon)
2. Submenu for existing panel module
_TRIPLE_ Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2959)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/471)
[Ticket](https://metaphase.atlassian.net/browse/TM-5960)
=> TM-5960: Panel Administrator Role

talentmap_api/fsbid/services/assignment_history.py, talentmap_api/fsbid/urls/assignment_history.py, talentmap_api/fsbid/views/assignment_history.py
- Standardized naming conventions
- Reordered code blocks
- Organized URLs and views to follow REST standards
- Made base request mapping functions for create/update on assignments and separations
- Only change in one place instead of multiple
- Adapted get assignments list to include separations list
- Corrected create separation endpoint
- Added update separation endpoint
- Added get separation detail endpoint
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2966)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/469)
[TM-5976](https://metaphase.atlassian.net/browse/TM-5976)
[TM-5977](https://metaphase.atlassian.net/browse/TM-5977)
[TM-5976]: https://metaphase.atlassian.net/browse/TM-5976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …
=> [TM-5976-5977] Maintain Separations/Assignments Integration and Refactor

talentmap_api/fsbid/views/agenda.py
FE already set up to handle a fail.
This is to handle when WS tells us something has failed, which is different from a fail on the actual WS call, which will be handled in the Except.
To simulate different fails:
**WS return fail**
in mock, for `app.delete('/v1/agendas/:aiseqnum'` change `return_code` to something other than 0
```
res.status(200).send({
Data: {},
usl_id: 0,
return_code: -1,
})
```
**WS call fail**
in mock, change the url to something random, that way our API won't find it and it will fail. This will process as a 422 return to our FE.
`app.delete('/v1/agendas/:aiseqnum', async function(req, res) {`
⬇️
`app.delete('/v1/somethingRandom/:aiseqnum', async function(req, res) {`
=> handle a WS fail return for Delete AI

talentmap_api/fsbid/views/admin_projected_vacancies.py, talentmap_api/fsbid/views/projected_vacancies.py
Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/3013)
[Ticket](https://metaphase.atlassian.net/browse/TM-6124)
=> TM-6124-Projected-Vacancies-API

talentmap_api/fsbid/services/panel.py
Dual Merge: 
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/506)
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/3070)
[Ticket](https://metaphase.atlassian.net/browse/TM-6409)
Updated panel remark mapping to include new data point
Verify
- on UI, you should see the word (Legacy) in front of panel remarks on panel meetings page
=> update panel remark mapping (api)

talentmap_api/fsbid/services/available_positions.py, talentmap_api/fsbid/services/projected_vacancies.py
Reverts MetaPhase-Consulting/State-TalentMAP-API#1072
Turns out it was working. Just bad data in dev1 keeping other flags from showing
=> Revert "Revert "TM-6348-DETO-RWA-Bidder-Position-Searches-Integration""
