MetaPhase-Consulting/State-TalentMAP-API

talentmap_api/bidding/serializers/serializers.py

We'll be displaying bid statistics on bid list-related UI elements so I added bid_statistics to the bid serializer.

Add bid_statistics to bidding serializer

---

talentmap_api/bidding/tests/test_bidlist.py
talentmap_api/bidding/views/bidlist.py
talentmap_api/common/tests/test_field_params.py
talentmap_api/position/models.py
talentmap_api/position/serializers.py
talentmap_api/position/views/position.py

- Trim down list serializer returns for position search
- Add availability information to position details for bidding button

Availability property

---

talentmap_api/common/management/commands/soap_api_test
talentmap_api/common/management/commands/soap_api_test.py

Updated `soap_api_test` command to pretty-print the response
Add file with example command to call and get 1 position back

Extra Soap Testing

---

talentmap_api/bidding/views/bidlist.py

allow a bid to be removed when the status is draft, submitted, and handshake offered

expand allowable statuses for removing a bid

---

talentmap_api/bidding/views/bidlist.py

changes were lost with conflicting PRs so this will add them back

fix: re-add missing change

---

talentmap_api/user_profile/serializers.py
talentmap_api/user_profile/tests/test_user_profile_endpoints.py
talentmap_api/user_profile/urls/profile.py
talentmap_api/user_profile/views/profile.py

Resolves TM-372.
Adds a new route to surface a 'public' profile. Currently using the short version of the profile.

feature: TM-372 - add route for public profile access

---

talentmap_api/integrations/models.py

- Force `last_updated_date` to local time zone
- Add hours to missing displays

FIX: SOAP Integration - Last Updated Date

---

talentmap_api/position/serializers.py

Only display the last name of the incumbent of a position. TM-445

fix: only display the last name of the incumbent on a position. TM-445

---

talentmap_api/position/serializers.py

Add `availability` to PositionList serializer to support https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/94

Add availability to PositionList

---

talentmap_api/position/serializers.py

Corrects the field used to for domestic posts

fix: correct value for non-dc domestic positions. TM-442

---

talentmap_api/bidding/models.py
talentmap_api/bidding/tests/test_bidlist.py

updates rules to allow positions with a handshake offer to accept bids

fix: allow positions with a handshake offer to accept other bids. TM-212

---

talentmap_api/position/serializers.py

Fixes issue identified in the demo from last sprint.

fix: get the correct info displaying on the position card for the domestic positions

---

talentmap_api/position/serializers.py

another issue that Cydney found when prepping for demo

fix: display correct info for a domestic bureau

---

talentmap_api/saml2/acs_patch.py

Comment out post_authenticated signal

---

EXAMPLE_setup_environment.sh

Based on transition to WatchedFileHandler and logrotate

Remove unused env vars

---

talentmap_api/fsbid/services.py

correctly maps the P bid status from FSBid to approved in TalentMap

fix: make P status from FSBid approved

---

talentmap_api/fsbid/services.py

Part of TM-909. Will do the rest in a different PR

fix: remove posted date from PV. TM-909

---

talentmap_api/bidding/models.py
talentmap_api/common/management/commands/update_relationships.py
talentmap_api/integrations/management/commands/import_data.py
talentmap_api/integrations/synchronization_helpers.py
talentmap_api/integrations/tests/test_soap_synchronization.py

needed so the same cycle position id is not added more than once

fix: set the collision field on cycle position

---

talentmap_api/integrations/urls/data_sync_actions.py
talentmap_api/integrations/views.py

Gives admin ability to call update_relationships command from and endpoint

added endpoint to run update_relationships command

---

talentmap_api/common/common_helpers.py
talentmap_api/fsbid/filters.py
talentmap_api/fsbid/views/projected_vacancies.py

Saves projected vacancy searches

feature: allow for saving projected vacancies searches. TM-642

---

talentmap_api/integrations/management/commands/schedule_synchronization_job.py

chore: add cycle position sync job to defaults list

---

talentmap_api/fsbid/services.py

I was using the old (non-cycle) position object structure for the PVs. This updates it so things display as expected.

fix: update the shape of the pv object to match new position shape

---

talentmap_api/bidding/models.py
talentmap_api/bidding/serializers/serializers.py
talentmap_api/bidding/views/bidlist.py

calculate availability for cycle position.

fix: update availability to use cycle position to allow bidding

---

talentmap_api/fsbid/services/projected_vacancies.py

fixes sorting on the pv endpoints.

fix: map talentmap sort fields to fsbid sort fields. TM-1207

---

talentmap_api/fsbid/services/bid_season.py

renamed the param to match what is in FSBid

fix: rename param. TM-1208

---

talentmap_api/fsbid/services/projected_vacancies.py

fixes the processing of the Domestic/Overseas filters to use the new FSBid filter option

fix: update the overseas filter. TM-1212

---

talentmap_api/common/common_helpers.py
talentmap_api/fsbid/filters.py
talentmap_api/user_profile/models.py
talentmap_api/user_profile/serializers.py
talentmap_api/user_profile/tests/test_saved_searches.py
talentmap_api/user_profile/views/searches.py

Refactor the update count function for the saved search model to be able to pass the jwt token to the api call.

Fix/update count. TM-1195

---

talentmap_api/integrations/synchronization_helpers.py

fix for the issues we are seeing in dev

fix: add defaults to the get_or_create on cycle position so it doesnt error

---

talentmap_api/integrations/management/commands/update_position_relationships_sql.py

this can be run via `python manage.py update_position_relationships_sql`

feature: allow for the update relationships sql to be run via a python command

---

talentmap_api/fsbid/services/common.py
talentmap_api/fsbid/services/projected_vacancies.py
talentmap_api/fsbid/tests/test_fsbid_projected_vacancies.py
talentmap_api/fsbid/urls/projected_vacancies.py
talentmap_api/fsbid/views/available_positions.py
talentmap_api/fsbid/views/base.py
talentmap_api/fsbid/views/bid_seasons.py
talentmap_api/fsbid/views/projected_vacancies.py

retreive an individual projected vacancy for use on something like the details page.

feature: get an individual projected vacancy.

---

talentmap_api/common/management/commands/update_relationships.py
talentmap_api/organization/models.py

do not create permissions, we dont use them.
change order of relationships so skills dont get forgotten

chore: cleanups for sync things

---

talentmap_api/fsbid/services/available_positions.py

Sets the limit on the number of similar positions

Fix limit on similar available positions. TM-1334

---

talentmap_api/fsbid/services/available_positions.py
talentmap_api/fsbid/services/common.py

this happens when searching for similar positions

fix: allow for location code to be passed to post available position filter. 

---

talentmap_api/user_profile/serializers.py

fixes the favorites not registering.

fix: return favorites as part of the user profile payload. TM-1338

---

talentmap_api/fsbid/services/bid.py
talentmap_api/fsbid/tests/test_fsbid_bidlist.py
talentmap_api/fsbid/views/bidlist.py

New mappings for bid data shape and cleans up some of the bidding functions. Requires the latest from mock-fsbid

fix: cleanup bidding and fsbid mappings. TM-1201

---

talentmap_api/fsbid/services/common.py

sort the available positions on the short bureau code field

fix: sort bureau on the short description. TM-1336

---

talentmap_api/fsbid/services/available_positions.py
talentmap_api/fsbid/services/projected_vacancies.py

uses the broken down location field to populate the location object

fix: use new broken down location field

---

talentmap_api/fsbid/services/reference.py
talentmap_api/fsbid/tests/test_fsbid_reference.py
talentmap_api/fsbid/urls/reference.py
talentmap_api/fsbid/views/reference.py

new endpoint for getting location data from the fsbid services

feature: add endpoint for getting location data from fsbid. TM-1386

---

talentmap_api/fsbid/services/bid.py

fix: add the ad_id param to the bidding endpoint queries. TM-1229

---

talentmap_api/log_viewer/services.py
talentmap_api/log_viewer/urls/log_entry.py
talentmap_api/log_viewer/views/log_entry.py

Unzips a compressed log file and streams contents as the response

feature: download and properly stream zipped files to the log download. TM-1324

---

talentmap_api/fsbid/services/available_positions.py

fixes filter mapping for using the reference data for filters

fix: fix the cycle filter. TM-1335

---

talentmap_api/fsbid/services/available_positions.py

Include capsule description in the available positions export

Include capsule description in export

---

talentmap_api/fsbid/services/reference.py
talentmap_api/fsbid/tests/test_fsbid_reference.py

Updates prop name mapping for the /location endpoint

Use correct prop names for mapping locations

---

requirements.txt
talentmap_api/fsbid/services/available_positions.py

Date formats returned from API do not include `Z` at the end. The use of this library should help with imperfect date formats.

Datetime parsing with the maya library

---

talentmap_api/fsbid/services/available_positions.py

I thought maya would automatically catch these, but we need a try/except to catch any null dates.

Catch errors for invalid datetimes in the available csv export

---

talentmap_api/fsbid/filters.py
talentmap_api/user_profile/models.py

make sure your front end is using the mock for available positions searching

fix: reenable saved search counts using the fsbid api. TM-1314

---

talentmap_api/fsbid/services/bid.py
talentmap_api/fsbid/tests/test_fsbid_bidlist.py

Related to https://github.com/MetaPhase-Consulting/mock-fsbid/pull/14

Add Data prop wrapper around bids

---

talentmap_api/fsbid/urls/cdo.py
talentmap_api/fsbid/views/cdo.py
talentmap_api/urls.py

cdo can add to bidlist, remove from bidlist and submit bids on behalf of a client

feature: cdo bidding on behalf of their client. TM-1393 TM-683 TM-685 TM-1370 TM-1396

---

talentmap_api/fsbid/views/cdo.py

I think there was a bad merge somewhere, because I also came across this when I combined the last two PRs myself locally.

Use correct service

---

talentmap_api/fsbid/views/client.py

addresses https://github.com/MetaPhase-Consulting/State-TalentMAP-API/pull/253#issuecomment-561671032

chore: update docs for get clients

---

talentmap_api/fsbid/services/client.py

resolves https://github.com/MetaPhase-Consulting/State-TalentMAP-API/pull/253#issuecomment-561681862

chore: return skills as an array

---

talentmap_api/fsbid/services/client.py
talentmap_api/fsbid/urls/client.py
talentmap_api/fsbid/views/client.py

use perdet_seq_num as the param

feature: add endpoint for getting single client TM-1374

---

talentmap_api/fsbid/services/client.py

Requires https://github.com/MetaPhase-Consulting/mock-fsbid/pull/18

fix: update client endpoint param names

---

talentmap_api/fsbid/services/client.py
talentmap_api/fsbid/views/client.py

requires https://github.com/MetaPhase-Consulting/mock-fsbid/pull/20/files
filter by the employees CDO hru_id

fix: filter clients by hru_id and not ad_id

---

talentmap_api/fsbid/services/bid.py

Filters out any bids where `bs_cd == 'D'`, as those are deleted and aren't mapped to the bid tracker.
Someone better at python could change this so that we filter out any bids that don't match an expected value. I should also update the front-end to gracefully handle any unexpected codes.

Filter out deleted bids

---

EXAMPLE_setup_environment.sh
deploy.sh
talentmap_api/fsbid/services/employee.py
talentmap_api/settings.py

sets a new env var for the Employee section of the fsbid api

fix: add a new var for the employee api root

---

talentmap_api/fsbid/services/bid.py

Use with https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/606

Update conditional to determine bid status and date

---

talentmap_api/fsbid/services/bid.py

Map In Panel dates and status, as well as the `U` (Unavailable) status

Map In Panel dates and status

---

talentmap_api/common/common_helpers.py
talentmap_api/settings.py
talentmap_api/user_profile/models.py
talentmap_api/user_profile/serializers.py

Generate profile picture URLs based on prefix in settings and user's email address

Generate profile picture URLs

---

talentmap_api/fsbid/services/client.py

Use with https://github.com/MetaPhase-Consulting/mock-fsbid/pull/29

Clients -> CDOClients

---

talentmap_api/fsbid/services/client.py
talentmap_api/fsbid/views/client.py

* Add hs_code param to client function
* Add hs_code param to conversion functions between fsbid and tmap
* Map "hs_code" to "handshake" for tmap

Update/add client hs filter TM-1488

---

talentmap_api/fsbid/services/available_positions.py
talentmap_api/fsbid/urls/available_positions.py
talentmap_api/fsbid/views/available_positions.py

Adds an endpoint to retrieve a single position by cp_id that is of cps_codes="FP".
~~@rtirserio to add mock functionality~~

Endpoint for a single filled (unavailable) position

---

talentmap_api/fsbid/services/client.py

- Remove csv fields for perdet

Remove csv fields for perdet seq on client export TM-1546

---

talentmap_api/fsbid/services/available_positions.py
talentmap_api/fsbid/services/common.py
talentmap_api/fsbid/services/projected_vacancies.py
talentmap_api/fsbid/views/available_positions.py
talentmap_api/fsbid/views/projected_vacancies.py

limits the export on PV to 2000 for non superusers and imposes no limit for superusers

TM-1556 TM-1584 fix: limit exports for not superusers to 2k

---

talentmap_api/fsbid/services/client.py
talentmap_api/fsbid/services/common.py

accepts multiple fields for sorting as a comma separated string

feature: allow multiple fields for sorting

---

talentmap_api/fsbid/services/available_positions.py

From an email that was sent about this

fix: use the override date for ted if its present

---

talentmap_api/fsbid/services/bid.py

Ensure any decimal in the bid ID removed

Convert perdet to string

---

talentmap_api/fsbid/views/cdo.py

only create cdo bid action notifications if the client has a user account in talentmap
Adding, submitting and removing will display the success message even when the client does not have a user account in talentmap

TM-1631 TM-1634 TM-1635 CDO bid action notification fix

---

talentmap_api/fsbid/services/client.py

Use with https://github.com/MetaPhase-Consulting/mock-fsbid/pull/48

Re-map perdet_seq_num

---

talentmap_api/fsbid/services/client.py

Requires https://github.com/MetaPhase-Consulting/mock-fsbid/pull/49

TM-1626 fix: correctly map the location for international and domestic locations

---

talentmap_api/fsbid/services/client.py
talentmap_api/fsbid/services/common.py
talentmap_api/fsbid/views/client.py

Use with https://github.com/MetaPhase-Consulting/mock-fsbid/pull/51

Integrate CDOClients pagination

---

talentmap_api/fsbid/services/client.py

Ensure different query without page size parameter is used when fetching CDOClients count

Pagination fix

---

talentmap_api/common/middleware.py
talentmap_api/fsbid/services/available_positions.py
talentmap_api/fsbid/services/projected_vacancies.py
talentmap_api/fsbid/views/available_positions.py
talentmap_api/fsbid/views/projected_vacancies.py

Include a header with the position export response indicating the position limit (if any) associated with the export.

Provide export limit as a new response header

---

talentmap_api/fsbid/services/bid.py
talentmap_api/fsbid/services/common.py
talentmap_api/fsbid/urls/bidlist.py
talentmap_api/fsbid/views/bidlist.py

- Adds endpoint to export current user's bidlist to CSV
- Comments out some fields we may want in the future once they are available (or pull their details by an additional network request)

Add ability to export bidlist to CSV

---

talentmap_api/common/common_helpers.py
talentmap_api/fsbid/services/available_positions.py
talentmap_api/fsbid/views/available_positions.py

Ticket: [TM-1589](https://metaphase.atlassian.net/browse/TM-1589)
Dual Merge: [FE PR #852](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/852)

Filter Handshake query params updated

---

talentmap_api/user_profile/serializers.py
talentmap_api/user_profile/tests/test_saved_searches.py

Disables field validation for saved searches.

Comment out saved search field validation

---

talentmap_api/fsbid/services/employee.py
talentmap_api/user_profile/serializers.py

- Use the new /Persons endpoint to retrieve the logged-in user's grade and skills.
Relies on https://github.com/MetaPhase-Consulting/mock-fsbid/pull/59, however some updates need to be made to that PR.

Get Employee info from /Persons endpoint - grade and skills

---

talentmap_api/fsbid/views/employee.py

Update the logic for the role cleanup so that roles that the user does in fact have are not deleted.

Fix role settings and deletion

---

talentmap_api/fsbid/services/available_positions.py
talentmap_api/fsbid/services/bid.py
talentmap_api/fsbid/services/cdo.py
talentmap_api/fsbid/services/common.py
talentmap_api/fsbid/urls/cdo.py
talentmap_api/fsbid/views/cdo.py

[TM-1785](https://metaphase.atlassian.net/browse/TM-1785)
[TM-1595](https://metaphase.atlassian.net/browse/TM-1595)

TM-1785: More fields added to BidList export. TM-1595: cdo client BidList export endpoint added.

---

talentmap_api/bidding/models.py
talentmap_api/fsbid/services/bid.py
talentmap_api/fsbid/urls/cdo.py
talentmap_api/fsbid/views/cdo.py
talentmap_api/user_profile/tests/test_client_endpoints.py

Note: the new status will break the front-end. Need to integrate.

Map register handshake status to bid

---

talentmap_api/fsbid/urls/available_positions.py
talentmap_api/fsbid/urls/projected_vacancies.py

Merge with https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/887

Placeholder endpoints for tandem

---

talentmap_api/fsbid/views/available_positions.py
talentmap_api/fsbid/views/projected_vacancies.py

- Adds common filter of postition__post_indicator__in to pv and ap tandem swagger

Add swagger docs for tandem common filter of post_ind

---

talentmap_api/available_positions/views/available_position.py

Ensures the page size matches the length of the favorites array

Set exports favorites page limit to length of favorites

---

talentmap_api/fsbid/views/reference.py

Use with https://github.com/MetaPhase-Consulting/mock-fsbid/pull/81

Use correct codeTableName

---

talentmap_api/fsbid/services/available_positions.py
talentmap_api/fsbid/services/common.py
talentmap_api/fsbid/services/projected_vacancies.py
talentmap_api/fsbid/urls/available_positions.py
talentmap_api/fsbid/urls/projected_vacancies.py
talentmap_api/fsbid/views/available_positions.py
talentmap_api/fsbid/views/projected_vacancies.py

- Adds tandem CSV export
- Fixes an issue where a check for if `ap: headers.append(smart_str(u"Capsule Description"))` caused a header/data mismatch
Use with https://github.com/MetaPhase-Consulting/mock-fsbid/pull/83

Tandem CSV Export

---

talentmap_api/fsbid/services/common.py
talentmap_api/settings.py

Return the internal and external versions of the OBC URL.
Use with https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/939

Return internal and external OBC URLs

---

talentmap_api/fsbid/services/available_positions.py
talentmap_api/fsbid/services/common.py
talentmap_api/fsbid/services/projected_vacancies.py

Merge #374 first
Use with https://github.com/MetaPhase-Consulting/mock-fsbid/pull/92
* Hard-codes the sort option when performing tandem search
* Use `partial` functions to more easily pass default function params

Map tandem filters sorting

---

talentmap_api/fsbid/services/available_positions.py
talentmap_api/fsbid/services/common.py
talentmap_api/fsbid/services/projected_vacancies.py

~~Merge https://github.com/MetaPhase-Consulting/State-TalentMAP-API/pull/376 first~~
@scott062 this will need the mock to be updated to use `count` param and `cnt` response property

Fix properties and params used for tandem counts

---

talentmap_api/available_positions/views/available_position.py
talentmap_api/fsbid/services/available_positions.py
talentmap_api/fsbid/services/projected_vacancies.py
talentmap_api/projected_vacancies/views/projected_vacancy.py

- Proposed changes to dev1 
- Add `archived=False` to a bunch of other class views in AP/PV

Add changes to archive favorites service methods

---

talentmap_api/fsbid/services/available_positions.py
talentmap_api/fsbid/services/projected_vacancies.py

- Fixes the count/tandem_count functions were swapped
- Passes `isTandem=True` to the mapping function for the tandem export

Tandem export/count fixes

---

talentmap_api/fsbid/urls/available_positions.py
talentmap_api/fsbid/views/available_positions.py

Dual Merge: [FE](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/1069)

grab random featured positions

---

docker-compose-api-only.yml
talentmap_api/fsbid/services/bureau.py
talentmap_api/fsbid/services/common.py
talentmap_api/fsbid/urls/bureau.py
talentmap_api/fsbid/views/bureau.py
talentmap_api/settings.py

Make sure you have the latest mock
Go to Swagger and hit `fsbid/bureau/positions/(some cp_id here)/bids/`

New endpoint for returning bids by a bureau cycleposition id

---

talentmap_api/common/management/commands/create_base_permissions.py
talentmap_api/fsbid/services/employee.py

Permission mapping for AO user.
Dual Merge: TBD

adding AO permissions

---

talentmap_api/fsbid/services/bureau.py
talentmap_api/fsbid/services/common.py

Use with https://github.com/MetaPhase-Consulting/mock-fsbid/pull/123

Update queries to reflect correct bureau positions URL

---

talentmap_api/fsbid/views/available_positions.py

testing the parameters to verify that the correct data is returned

adding swagger documentation for featured positions

---

talentmap_api/stats/urls/logins.py
talentmap_api/stats/views.py

System monitoring endpoint:
- Returns memory, CPU and disk statistics
- Limited to superuser only

Add system monitoring endpoint

---

talentmap_api/available_tandem/views/available_tandem.py
talentmap_api/projected_tandem/views/projected_tandem.py

Adding ordering
PS: my mock is jacked, so I can't test if this is actually a "fix" lol

fixing tandem favorites sorting

---

talentmap_api/available_tandem/views/available_tandem.py
talentmap_api/projected_tandem/views/projected_tandem.py

Reverts MetaPhase-Consulting/State-TalentMAP-API#419

Revert "fixing tandem favorites sorting"

---

talentmap_api/fsbid/services/client.py
talentmap_api/fsbid/services/employee.py
talentmap_api/user_profile/serializers.py

Fixes an issue when trying to migrate

Don't import recursively

---

talentmap_api/available_positions/views/available_position.py
talentmap_api/fsbid/views/bureau.py

- Add `is_locked` to bureau position by id
- Update permissions so that post_users can still see the ranking of locked positions

Bureau rank fixes

---

talentmap_api/fsbid/services/employee.py

Thought we had already fixed this but I guess not 🤷‍♂️

Convert single role to an array

---

requirements.txt

Fixes an issue building dependencies

Upgrade zope.interface

---

EXAMPLE_setup_environment.sh
deploy.sh
docker-compose-api-only.yml
talentmap_api/settings.py

Dual Merge: [FE](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/1375) & [Mock](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/154)

updates to user info

---

talentmap_api/user_profile/management/commands/create_seeded_users.py

seeding Abigail

---

talentmap_api/fsbid/services/client.py

Use with https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/1404

AB integration fixes

---

talentmap_api/fsbid/services/bureau.py
talentmap_api/fsbid/services/common.py
talentmap_api/fsbid/views/bureau.py

just adding csv export functionality for [this PR](https://github.com/MetaPhase-Consulting/State-TalentMAP-API/pull/496)

adding new hs data to csv

---

requirements.txt
talentmap_api/settings.py
talentmap_api/urls.py

Fixes swagger by using a new library

Fix swagger

---

talentmap_api/bureau/services/available_bidders.py
talentmap_api/cdo/services/available_bidders.py
talentmap_api/common/common_helpers.py

never tried the assignees thing before. Let's try it!

update to formatCSV

---

talentmap_api/common/common_helpers.py
talentmap_api/fsbid/services/bid.py

Threading allows the `send_email` function to run in the background as a non-blocking thread. You can test by modifying the code to:
```py
def send_email_thread(subject = '', body = '', recipients = []):
import time
time.sleep(10)
if EMAIL_ENABLED:
...
```
Registering a handshake should return a success notification instantly, but the email won't be sent until 10 seconds later.

Implement threading for email function

---

talentmap_api/common/common_helpers.py
talentmap_api/fsbid/services/bureau.py
talentmap_api/fsbid/views/cdo.py

Use with https://github.com/MetaPhase-Consulting/mock-fsbid/pull/181
All other bidders of a position will be notified when a CDO registers or unregisters a handshake on a bid in their bid list.

Email bidders when a CDO registers/unregisters HS

---

talentmap_api/fsbid/services/client.py

Closed [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/1511). Changes are only need on the BE.

reordering name on client card profile

---

SETUP.md
talentmap_api/common/management/commands/create_demo_environment.py
talentmap_api/organization/management/commands/create_obc.py

Add create_obc command in order to load db with obc links

---

talentmap_api/fsbid/services/common.py

rip found another one: bidlist update fix 
for reference: [this PR](https://github.com/MetaPhase-Consulting/State-TalentMAP-API/pull/534)

position update for csv

---

talentmap_api/fsbid/services/bureau.py

Use with https://github.com/MetaPhase-Consulting/mock-fsbid/pull/189

Use correct path for determining email of bidder

---

requirements.txt

Fixes compatibility with https://github.com/MetaPhase-Consulting/State-TalentMAP-API/pull/553

Bump to requests 2.25.1

---

talentmap_api/common/common_helpers.py

To be used for: [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/1573)

action metadata

---

talentmap_api/user_profile/serializers.py

Return the user's current assignment in their private profile

Add current assignment to the private profile

---

talentmap_api/fsbid/services/common.py

export included the whole bidcycle obj

fix for bidlist export

---

talentmap_api/fsbid/services/client.py

So that client email address is included in the CSV export from the Client Portfolio

Add client email to export

---

requirements.txt
talentmap_api/fsbid/services/bureau.py
talentmap_api/fsbid/services/common.py
talentmap_api/fsbid/services/reference.py

Merge #584 first
Adds a new field, `has_accepted_other_offer`, which indicates whether the bidder has accepted a handshake for a cycle position that is in an active bid cycle
Note:
- you'll need to re-install dependencies
- you'll need to run migrations

"has accepted handshake" indicator

---

talentmap_api/glossary/urls/glossary.py
talentmap_api/glossary/views/glossary.py

Exports entire glossary (excluding archived terms)

Add export endpoint for glossary

---

talentmap_api/fsbid/services/common.py

Use the actual, populated SND property for the export

Fix for SND export value

---

talentmap_api/fsbid/services/available_positions.py
talentmap_api/fsbid/services/common.py
talentmap_api/fsbid/services/projected_vacancies.py

Secondary skill code was previously not mapped for projected vacancies. Use with https://github.com/MetaPhase-Consulting/mock-fsbid/pull/217

Add secondary skill for PVs; refactor logic

---

talentmap_api/fsbid/services/cdo.py

I'll cherry pick this into last release once reviewed

Add request_params.

---

talentmap_api/fsbid/services/common.py

Use with https://github.com/MetaPhase-Consulting/mock-fsbid/pull/222

Add middle name to sort map

---

talentmap_api/cdo/services/available_bidders.py
talentmap_api/fsbid/services/common.py

Updates all True/False values to use the `mapBool` mapping to Yes/No

Fix export true/false values

---

talentmap_api/fsbid/services/common.py

SND added to PV (was already for AP)
HDS added to both

SND HDS added to export TM-2393

---

docker-compose-api-only.yml
docker-compose.yml
talentmap_api/fsbid/services/available_positions.py
talentmap_api/fsbid/services/common.py
talentmap_api/fsbid/services/projected_vacancies.py
talentmap_api/settings.py

Use with https://github.com/MetaPhase-Consulting/mock-fsbid/pull/225

Use POST endpoints

---

talentmap_api/fsbid/services/bureau.py

Dual Merge: [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/1785) [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/235)
~Blocker: ws to add to cycleposition/bidders -  asked for it 9.28.21~

HS Register info

---

talentmap_api/fsbid/views/classifications.py

- Fixes missing classifications on private profile (typo)

Fix singular classifications

---

talentmap_api/available_positions/views/available_position.py
talentmap_api/available_tandem/views/available_tandem.py
talentmap_api/bidding/views/bidhandshake.py
talentmap_api/bureau/views/available_bidders.py
talentmap_api/cdo/views/available_bidders.py
talentmap_api/fsbid/views/available_positions.py
talentmap_api/fsbid/views/bureau.py
talentmap_api/fsbid/views/classifications.py
talentmap_api/fsbid/views/client.py
talentmap_api/fsbid/views/projected_vacancies.py
talentmap_api/log_viewer/views/log_entry.py
talentmap_api/projected_tandem/views/projected_tandem.py
talentmap_api/projected_vacancies/views/projected_vacancy.py

Use `drf_yasg` for manual schemas since that's what we now use for swagger

Fix manual swagger schemas with use of drf_yasg

---

talentmap_api/fsbid/services/bureau.py

use with https://github.com/MetaPhase-Consulting/mock-fsbid/pull/244

ubw-hs mapping

---

talentmap_api/fsbid/services/client.py

- Use the correct identifier for fetching the employee profile (employee ID, not perdet)
- Use pydash.get to avoid one non-existent prop triggering an error in the try/except

Employee fixes

---

.github/workflows/codeql-analysis.yml
docker-compose-api-only.yml
docker-compose.yml
talentmap_api/settings.py

Run as
`REPLICAS=3 docker-compose -f docker-compose-api-only.yml up`
Change `REPLICAS` value to however many replicas you want

Docker replicas

---

talentmap_api/fsbid/views/bureau.py
talentmap_api/permission/views/user.py

Dual Merge: [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/1882)
It ain't pretty, but it works :/

sorting and single filter working

---

docker-compose-api-only.yml
talentmap_api/fsbid/services/client.py

- Use hru_id to fetch employee profile
- Remove unused employee profile mapping from available bidders response
- Add HRDATA environment variables

Use hru_id to fetch employee profile report

---

requirements.txt
talentmap_api/settings.py
talentmap_api/urls.py

Health check endpoint is http://localhost:8000/ht/
You'll need install dependencies and run a migration

Add health check endpoint

---

talentmap_api/fsbid/services/available_positions.py
talentmap_api/fsbid/services/projected_vacancies.py

Can't test this against mock, but this is how WS needs this value to be sent over.

Wrap overseas/domestic filter in array

---

docker-compose-api-only.yml
docker-compose.yml
talentmap_api/fsbid/services/agenda.py
talentmap_api/fsbid/services/common.py
talentmap_api/fsbid/urls/agenda.py
talentmap_api/fsbid/views/agenda.py
talentmap_api/settings.py
talentmap_api/urls.py

Use with https://github.com/MetaPhase-Consulting/mock-fsbid/pull/245

Agenda Item Endpoint

---

talentmap_api/fsbid/services/agenda.py
talentmap_api/fsbid/services/common.py
talentmap_api/fsbid/urls/agenda.py
talentmap_api/fsbid/views/agenda.py

[FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/1893)

agenda item history export

---

docker-compose-api-only.yml
talentmap_api/fsbid/services/agenda_employees.py
talentmap_api/fsbid/urls/agenda_employees.py
talentmap_api/fsbid/views/agenda_employees.py
talentmap_api/settings.py
talentmap_api/urls.py

* Requires mock PR for new v3/persons -> https://github.com/MetaPhase-Consulting/mock-fsbid/pull/250
* waiting for finalized payload (see commented code)

Add new urls,views,services for agenda_employees

---

talentmap_api/fsbid/services/agenda_employees.py

Tagging @scott062 for awareness

Do best guess of user intent when searching for letters and/or numbers

---

talentmap_api/fsbid/services/agenda_employees.py
talentmap_api/fsbid/services/common.py

Added new sorts for employee Search
- First Name 
- Last Name 
- Employee ID 
- Full Name
DM: https://github.com/MetaPhase-Consulting/mock-fsbid/pull/255

Agenda Employee Search Sorts TM-2491

---

talentmap_api/fsbid/services/common.py

Forces string formatting of positions numbers so that leading 0s are not omitted.
---
No new endpoints

Format position numbers as strings

---

talentmap_api/fsbid/views/agenda.py

Had the permission name wrong. We use `ao_user` not `ao`, so this permission check never did anything.
---

ao_user permission fix

---

talentmap_api/user_profile/management/commands/create_seeded_users.py

Seeding Tarek a new role
To test:
Check Tarek's permissions before running following command
Run `create_demo_environment` - Tarek should now have helppage_editor role
~- [ ] Postman tests for any new endpoints~ AWS Specific

tarek new role

---

talentmap_api/fsbid/services/agenda.py
talentmap_api/fsbid/services/common.py

Dual Merge: [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/1980)
~- [ ] Postman tests for any new endpoints~ NA

Adding abbreviated status to agenda payload

---

talentmap_api/fsbid/services/cdo.py

Deduplicates CDOs
---
- ~~[ ] Postman tests for any new endpoints~~

Deduplicate CDOs

---

.gitignore
docker-compose-cloud.yml

Create an `.env` file with the following contents:
```
ORACLE_URL=xxxxxxxxxxx_high
ORACLE_USER=xxxxxxx
ORACLE_PW=xxxxxxxxxxxxxx
```

Use oracle cloud instance

---

talentmap_api/fsbid/services/available_positions.py

-- Enter PR description here --
---

favorites archive fix

---

talentmap_api/fsbid/services/bureau.py

-- Enter PR description here --
---

reverting to previous employee name grab

---

talentmap_api/fsbid/services/agenda.py

[FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2104)
To-do:
**Note:** choose not to add a column for the employee name as it would be only one row (we don't do this for any other exports) and the name is already in the filename so AO's/CDO's will be able to identify the client the AIH export is for.

aih employee name export

---

TM_Version.txt
talentmap_api/fsbid/services/common.py

-- Enter PR description here --
---

api versioning file

---

talentmap_api/fsbid/services/common.py

To resolve prd language issue reported to us 6.29.22

regex handling symbols

---

.github/pull_request_template.md

-- Enter PR description here --
---

updating PR template file

---

talentmap_api/fsbid/views/reference.py

Rename ref data endpoint to match WS
Dual Merge: 
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/294)

Rename post attribute endpoints

---

.github/pull_request_template.md
docker-compose-api-only.yml
docker-compose-cloud.yml
talentmap_api/common/common_helpers.py
talentmap_api/fsbid/services/common.py
talentmap_api/fsbid/services/positions.py
talentmap_api/fsbid/urls/positions.py
talentmap_api/fsbid/views/positions.py
talentmap_api/settings.py

Create Generic Positions url
Dual Merge: 
- [FE PR ](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2246)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/295)

Creating generic positions url

---

talentmap_api/fsbid/services/assignment_history.py
talentmap_api/fsbid/services/bid.py
talentmap_api/fsbid/services/employee.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2266)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/299)

Update mapping for new position node

---

talentmap_api/fsbid/services/assignment_history.py

Still more to do, but this makes it a little more accurate

Update mappings for assignments

---

talentmap_api/fsbid/services/agenda.py
talentmap_api/fsbid/services/common.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2267)
To-do

refactor for remarks pill

---

talentmap_api/fsbid/services/assignment_history.py

Reverts MetaPhase-Consulting/State-TalentMAP-API#706

Revert "Update mappings for assignments"

---

talentmap_api/fsbid/services/bid.py

Add first element of position array mapping

---

talentmap_api/bureau/views/available_bidders.py

Dual Merge
- [FE](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2306)
Addresses:
- AO/CDO being unable to export External CDA ABL View

fix for 9.0 uat bugs

---

talentmap_api/fsbid/services/client.py

- Updated logic to strip whitespace in languages array/element

Stripped whitespace from the elements

---

talentmap_api/bureau/services/available_bidders.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2345)
To-do:

adding updated columnn to external abl export

---

talentmap_api/fsbid/services/common.py

- Cleaning up filename to fix Response header Content-Disposition error

Added regex to cleanup filename

---

docker-compose-api-only.yml
docker-compose-cloud.yml
talentmap_api/fsbid/services/positions.py
talentmap_api/fsbid/urls/positions.py
talentmap_api/fsbid/views/positions.py
talentmap_api/settings.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2381)

frequent positions endpoint

---

talentmap_api/fsbid/services/agenda.py

Dual Merge: 
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/319)

mapping for creators and updaters

---

talentmap_api/fsbid/services/positions.py

Fix for this PR
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2400)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/321)

handling bad fp data TM-3233

---

talentmap_api/fsbid/services/agenda.py
talentmap_api/fsbid/services/common.py
talentmap_api/fsbid/urls/panel.py
talentmap_api/fsbid/views/agenda.py
talentmap_api/urls.py

Dual Merge: 
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/324)

TM-3681: Agendas by Panel Date EP

---

talentmap_api/permission/tests/test_permission_endpoints.py
talentmap_api/permission/urls/user.py
talentmap_api/permission/views/user.py

Ensure permissions by id is limited to superuser django role
Testing:

Update permissions for user/permission endpoint

---

talentmap_api/fsbid/services/panel.py
talentmap_api/fsbid/urls/panel.py
talentmap_api/fsbid/views/agenda.py
talentmap_api/urls.py

Dual Merge:
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2443)

Organizing and Optimizing

---

talentmap_api/fsbid/services/agenda_employees.py
talentmap_api/fsbid/services/common.py
talentmap_api/fsbid/services/panel.py
talentmap_api/fsbid/urls/panel.py
talentmap_api/fsbid/views/panel.py

Dual Merge:
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2447)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/330)
Branched off of https://github.com/MetaPhase-Consulting/State-TalentMAP-API/pull/739 so this PR looks a bit bigger

TM-3939 and TM-3709 panel meetings EP

---

talentmap_api/fsbid/services/panel.py

Fix for Panel filters multiple values for same filter

IN for Panel filters

---

talentmap_api/fsbid/services/common.py
talentmap_api/fsbid/services/panel.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2458)

panel meeting sorts

---

talentmap_api/fsbid/services/agenda_employees.py

Changing matching on `tmperperfullname` for both first and last name to `tmperperfirstname` and `tmperperlastname` respectively

TM-3875: Changing filters to match new WS fields

---

talentmap_api/fsbid/services/agenda.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2439)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/335)
To-do:

adding report category & panel date type TM-3929

---

talentmap_api/fsbid/services/agenda.py
talentmap_api/fsbid/views/agenda.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2461)

panel meeting sections

---

talentmap_api/fsbid/services/agenda.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2439)
To-do:

adding ailseqnum to ai legs TM-3910

---

talentmap_api/fsbid/services/agenda.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2469)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/342)

mapping pmi-official-item-number and hard-coding sort TM-4003

---

talentmap_api/fsbid/services/common.py
talentmap_api/fsbid/services/panel.py
talentmap_api/fsbid/urls/panel.py
talentmap_api/fsbid/views/panel.py

ACs:
1. Verify export button is working and csv file is downloading successfully
Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2472)

TM-3952: Panel Meetings Export Endpoint

---

talentmap_api/fsbid/services/panel.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2470)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/345)
To-do

panel meeting search pagination TM-4024

---

talentmap_api/fsbid/services/panel.py

csvQuery['limit'] down to 1000 instead of 2000

TM-3852 Fix: decreasing export limit to 1000

---

talentmap_api/fsbid/services/agenda.py

[FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2478)

Fail elegantly with no jwt

---

talentmap_api/fsbid/services/client.py

Still need to deep dive why perdets aren't returning clients on WS side - this prevents the page from entirely erroring

Wrap index error in try TM-4139

---

talentmap_api/fsbid/services/agenda.py
talentmap_api/fsbid/services/common.py
talentmap_api/fsbid/urls/panel.py
talentmap_api/fsbid/views/agenda.py

ACs:
1. Verify new export agendas by panel id EP is functional and export file is accurate
Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2481)

TM-4137: export agendas by panel meeting

---

talentmap_api/fsbid/services/common.py

Forgot to add fallback for new helper date function. Causing DEV1 to break

TM-4137: adding fallback for date processing function

---

talentmap_api/fsbid/services/common.py
talentmap_api/fsbid/services/panel.py
talentmap_api/fsbid/views/panel.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2483)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/352)

updating Panel Meetings filters and sort

---

talentmap_api/fsbid/services/agenda.py
talentmap_api/fsbid/services/common.py
talentmap_api/fsbid/views/agenda.py

https://metaphase.atlassian.net/browse/TM-4030
---
ACs:
1. Verify 'CDO', 'Creator(s)', and 'Modifier(s)' remarks are not showing up on the panel meeting agendas screen and also not showing up on agenda item history
[Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/347)

TM-4030: removing creator/modifier remarks

---

talentmap_api/fsbid/services/agenda_employees.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2486)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/354)

adding pmseqnum to eas payload TM-4033

---

talentmap_api/fsbid/services/agenda.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2485)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/353)

TM-4134, return dates for agenda items

---

talentmap_api/fsbid/services/agenda.py
talentmap_api/fsbid/services/common.py

add remarks to aih & pma export TM-4136

---

talentmap_api/fsbid/services/panel.py

When selecting the same day on the date filter for panel meetings, it would not return the panel meetings for that day

TM-4197 setting filter date to next day

---

talentmap_api/fsbid/services/assignment_history.py

This is why we open PRs instead of committing to dev

Add fields to hard coded requests

---

talentmap_api/fsbid/services/agenda_employees.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2520)

pulling id

---

talentmap_api/fsbid/services/agenda.py

https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2555

Fix for eta for retire

---

talentmap_api/fsbid/services/agenda.py

Looking pretty good - there is still no handling for multiple incumbents ... might have to make a follow on ticket for that, unless it would be something simple to jimmy in the mock 🤔
Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2590)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/376)
[Ticket](https://metaphase.atlassian.net/browse/TM-4306)

TM-4306, add vice to agenda items

---

talentmap_api/fsbid/services/agenda.py

Vice Bugfix

---

talentmap_api/fsbid/services/admin_panel.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2604)
[Ticket](https://metaphase.atlassian.net/browse/TM-4448)

defaulting mutuallyExclusive to N TM-4448

---

talentmap_api/fsbid/services/assignment_history.py
talentmap_api/fsbid/services/common.py
talentmap_api/fsbid/views/assignment_history.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2640)
[Ticket](https://metaphase.atlassian.net/browse/TM-3088)

TM-3088, sort ass history by start date

---

TM_Version.txt

[FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2662)
11.0 🥳

TM Version 11.0

---

talentmap_api/fsbid/services/agenda.py
talentmap_api/fsbid/services/employee.py
talentmap_api/fsbid/services/positions.py

Mapping new pay plan fields from EP 
Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2651)
[Ticket](https://metaphase.atlassian.net/browse/TM-4521)

TM-4521: Pay Plan field - Panel Agenda items

---

docker-compose-api-only.yml
docker-compose-cloud.yml
talentmap_api/fsbid/services/client.py
talentmap_api/fsbid/services/common.py
talentmap_api/fsbid/services/employee.py
talentmap_api/fsbid/urls/employee.py
talentmap_api/fsbid/views/client.py
talentmap_api/fsbid/views/employee.py
talentmap_api/settings.py
talentmap_api/user_profile/serializers.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2671)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/390)
[TM-4894](https://metaphase.atlassian.net/browse/TM-4894)
[TM-4894]: https://metaphase.atlassian.net/browse/TM-4894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TM-4894 emp profile to api call

---

talentmap_api/fsbid/services/agenda.py
talentmap_api/fsbid/services/common.py
talentmap_api/fsbid/services/remark.py
talentmap_api/fsbid/urls/remark.py
talentmap_api/fsbid/views/remark.py

FE: https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2692
API: https://github.com/MetaPhase-Consulting/State-TalentMAP-API/pull/839
Mock: https://github.com/MetaPhase-Consulting/mock-fsbid/pull/401

Edit Remark

---

talentmap_api/fsbid/services/post_access.py

Needed some updates for changes we made to deploy PP - snuck in some other ones too tho

response update - Search Post Access

---

talentmap_api/fsbid/services/job_categories.py

Needed some updates for changes we made to deploy PP - snuck in some other ones too tho

response update - Job Categories

---

talentmap_api/fsbid/services/common.py
talentmap_api/fsbid/services/post_access.py
talentmap_api/fsbid/views/post_access.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2687/files)
[Ticket](https://metaphase.atlassian.net/browse/TM-4848)

TM-4848, Manage Post Access API

---

talentmap_api/fsbid/services/job_categories.py
talentmap_api/fsbid/urls/job_categories.py
talentmap_api/fsbid/views/job_categories.py

As far as local testing goes, I left logger.info lines in the API for edit, create, and delete. You can take that JSON and drop it into DEV1 swagger
Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2727)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/402)
[Ticket](https://metaphase.atlassian.net/browse/TM-4846)

TM-4846: Job Category support for saving new category

---

talentmap_api/fsbid/services/agenda.py
talentmap_api/fsbid/services/agenda_item_validator.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2745)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/408)
[Ticket](https://metaphase.atlassian.net/browse/TM-2493)

TM-2493, TM-4998 add combined TOD to AIM page

---

talentmap_api/fsbid/services/job_categories.py

just removing the debug logger lines
Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2738)

Job Categories: Removing logging statements

---

talentmap_api/fsbid/services/agenda.py

Dual Merge: Small change had to be made to pre-existing BE and FE code.
https://metaphase.atlassian.net/browse/TM-4991
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2749)
- [BE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP-API/pull/855)

TM-4991-Panel-View-BE

---

talentmap_api/common/common_helpers.py
talentmap_api/fsbid/services/admin_panel.py
talentmap_api/fsbid/urls/admin_panel.py
talentmap_api/fsbid/views/admin_panel.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2739)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/407)
[TM-4843](https://metaphase.atlassian.net/browse/TM-4843)
[TM-4843]: https://metaphase.atlassian.net/browse/TM-4843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TM-4843] Run Panel Integration

---

talentmap_api/fsbid/services/assignment_history.py

[Ticket](https://metaphase.atlassian.net/browse/TM-5009)
In Dev (will fallback to using the code, if the text does not exist - so, locally will have the code)

TM-5009 Assignment History Status

---

talentmap_api/fsbid/services/bureau_exceptions.py
talentmap_api/fsbid/urls/bureau_exceptions.py
talentmap_api/fsbid/views/bureau_exceptions.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2766)
---
1. Integrating with bureau ref data that has the long description for Bureaus
2. Refactoring
[TM-5070](https://metaphase.atlassian.net/browse/TM-5070)
[TM-5070]: https://metaphase.atlassian.net/browse/TM-5070?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TM-5070 Pt2 - BEL Refactor

---

talentmap_api/fsbid/services/bureau_exceptions.py
talentmap_api/fsbid/services/common.py
talentmap_api/fsbid/views/bureau_exceptions.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2786)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/419)
[Ticket](https://metaphase.atlassian.net/browse/TM-5247)

Bel updates

---

talentmap_api/fsbid/services/bidding_tool.py
talentmap_api/fsbid/urls/bidding_tool.py
talentmap_api/fsbid/views/bidding_tool.py
talentmap_api/urls.py

Updates:
- Added Bidding Tool URLS
- Added Bidding Tool Views
- Attempted to optimize the endpoints to be under the same base URL
- 
- Adding Bidding Tool Service Functions
- Get list function
Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2791)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/420)
[TM-4919](https://metaphase.atlassian.net/browse/TM-4919)
[TM-4919]: https://metaphase.atlassian.net/browse/TM-4919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TM-4919] Bidding Tool Integration

---

talentmap_api/fsbid/services/bidding_tool.py
talentmap_api/fsbid/views/bidding_tool.py

Fixes:
- Procedure Name
- Roles
[TM-4919](https://metaphase.atlassian.net/browse/TM-4919)
[TM-4919]: https://metaphase.atlassian.net/browse/TM-4919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TM-4919] Bidding Tool Integration Patches v1

---

talentmap_api/fsbid/services/assignment_cycles.py
talentmap_api/fsbid/urls/assignment_cycles.py
talentmap_api/fsbid/views/assignment_cycles.py

PART 2 of Assignment Cycles
PART 1 - https://github.com/MetaPhase-Consulting/State-TalentMAP-API/pull/886
Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2813)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/429)
[Ticket](https://metaphase.atlassian.net/browse/TM-5413)
[Ticket](https://metaphase.atlassian.net/browse/TM-4909)

TM-5413 - create new assignment cycle

---

talentmap_api/fsbid/services/agenda_item_validator.py

[Ticket](https://metaphase.atlassian.net/browse/TM-5448)
Makes TOD, ETA, and TED not required for separation leg.

update validation for separation

---

talentmap_api/fsbid/services/agenda.py

no create metadata on edit

---

talentmap_api/fsbid/services/agenda_item_validator.py

confirmed with scott that travel is not required

remove validation check for travel

---

talentmap_api/fsbid/services/agenda.py

edge case handling for separations

---

talentmap_api/fsbid/services/agenda_item_validator.py

[Ticket](https://metaphase.atlassian.net/browse/TM-5481)

TM-5481, TED validation for TOD of indefinite and n/a

---

talentmap_api/fsbid/services/common.py

[Ticket](https://metaphase.atlassian.net/jira/software/c/projects/TM/boards/1?assignee=712020%3Ae4af8680-bb45-4f2a-99eb-24b8dd8e13c4&selectedIssue=TM-5474#:~:text=TM%2D3676-,TM%2D5474,-1)
-Renamed  “Handshake needs registered” to “Active” so that it will be clearer for the bidder to understand the position is still active and without a handshake.

TM-5474-Bid Tracker Update - Rename

---

talentmap_api/common/common_helpers.py
talentmap_api/fsbid/services/admin_panel.py
talentmap_api/fsbid/views/admin_panel.py

[UI](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2829)

[TM-5071] Fix Run Panel Issues

---

talentmap_api/fsbid/services/agenda.py

[FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2834)
[Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/430)

TM-4990: Panel Meetings Missing Emp Info

---

talentmap_api/common/common_helpers.py
talentmap_api/fsbid/services/agenda.py

add fallback logic for agendas with no sort date to sort

---

talentmap_api/fsbid/services/remark.py

Create Remarks is failing on DEV1 due to Oracle refusing an empty short description field

Create Remarks Fix

---

talentmap_api/fsbid/services/agenda.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2841)
[Ticket](https://metaphase.atlassian.net/browse/TM-5480)

TM-5480, separation location

---

talentmap_api/fsbid/services/assignment_cycles.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2852)
[TM-5549](https://metaphase.atlassian.net/browse/TM-5549)
[TM-5549]: https://metaphase.atlassian.net/browse/TM-5549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

handle empties

---

talentmap_api/fsbid/services/agenda.py
talentmap_api/fsbid/services/agenda_item_validator.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2895)
[TM-5541](https://metaphase.atlassian.net/browse/TM-5541)
---
1. re-add Travel Validation
2. get set up for expected WS travel desc return
[TM-5541]: https://metaphase.atlassian.net/browse/TM-5541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TM-5541] Travel Updates

---

talentmap_api/fsbid/services/agenda.py

Dual Merge: 
[TM-5696](https://metaphase.atlassian.net/browse/TM-5696)
[TM-5696]: https://metaphase.atlassian.net/browse/TM-5696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

travel desc from ws

---

talentmap_api/fsbid/services/assignment_cycles.py
talentmap_api/fsbid/views/assignment_cycles.py

Merge cycle hotfix

---

TM_Version.txt

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2916)

Release 12.1

---

talentmap_api/fsbid/services/client.py

ACs:
1. Verify skill code now shows up in client profile export
[Ticket](https://metaphase.atlassian.net/browse/TM-5832)

adding skill code to export

---

talentmap_api/fsbid/services/assignment_cycles.py
talentmap_api/fsbid/urls/assignment_cycles.py
talentmap_api/fsbid/views/assignment_cycles.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2939)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/462)
[Ticket](https://metaphase.atlassian.net/browse/TM-5807)

TM-5807, cycle date classifications

---

talentmap_api/fsbid/services/bid_audit.py
talentmap_api/fsbid/urls/bid_audit.py
talentmap_api/fsbid/views/bid_audit.py
talentmap_api/urls.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2956)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/467)
[Ticket](https://metaphase.atlassian.net/browse/TM-5875)

TM-5875, Bid Audit API

---

talentmap_api/fsbid/services/publishable_positions.py

Just something I noticed during demo
Dual Merge:
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2964)

comment out not integrated fields

---

talentmap_api/fsbid/services/bid_audit.py
talentmap_api/fsbid/urls/bid_audit.py
talentmap_api/fsbid/views/bid_audit.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2965)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/468)
[Ticket](https://metaphase.atlassian.net/browse/TM-5874)

TM-5874, Run Bid Audit

---

talentmap_api/fsbid/services/bid_audit.py
talentmap_api/fsbid/urls/bid_audit.py
talentmap_api/fsbid/views/bid_audit.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2970)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/472)
[Ticket](https://metaphase.atlassian.net/browse/TM-5878)

TM-5878, Update Bid Audit

---

talentmap_api/fsbid/services/employee.py
talentmap_api/fsbid/urls/employee.py
talentmap_api/fsbid/views/employee.py

Expose `get_user_information` directly
Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2962)
[TM-5855](https://metaphase.atlassian.net/browse/TM-5855)
[TM-5855]: https://metaphase.atlassian.net/browse/TM-5855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Civil Service Emp Profile

---

talentmap_api/fsbid/services/agenda.py
talentmap_api/fsbid/urls/agenda.py
talentmap_api/fsbid/views/agenda.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2969)
[Ticket](https://metaphase.atlassian.net/browse/TM-5944)

TM-5944-Agenda-Item-Delete-API

---

talentmap_api/fsbid/services/assignment_cycles.py
talentmap_api/fsbid/urls/assignment_cycles.py
talentmap_api/fsbid/views/assignment_cycles.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2971)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/473)
[Ticket](https://metaphase.atlassian.net/browse/TM-5671)

TM-5671, Edit Cycle Position Details

---

talentmap_api/fsbid/services/assignment_history.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2982)
[TM-5984](https://metaphase.atlassian.net/browse/TM-5984)
[TM-5984]: https://metaphase.atlassian.net/browse/TM-5984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TM-5984] Maintain Assignments Remediation

---

talentmap_api/fsbid/views/admin_panel.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2985)
[TM-5961](https://metaphase.atlassian.net/browse/TM-5961)
[TM-5961]: https://metaphase.atlassian.net/browse/TM-5961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TM-5961] Deconflict FSBID and Panel Admin Features

---

talentmap_api/fsbid/services/bid_audit.py
talentmap_api/fsbid/urls/bid_audit.py
talentmap_api/fsbid/views/bid_audit.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2988)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/475)
[Ticket](https://metaphase.atlassian.net/browse/TM-5912)
[Ticket](https://metaphase.atlassian.net/browse/TM-5877)

TM-5912, TM-5877, Bid Audit - Create In Category & At Grade

---

talentmap_api/fsbid/views/agenda.py

Dual Merge: 
[Ticket](linkToTicket)

wrong return code syntax

---

talentmap_api/fsbid/services/assignment_history.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2992)
[TM-6144](https://metaphase.atlassian.net/browse/TM-6144)
[TM-6144]: https://metaphase.atlassian.net/browse/TM-6144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TM-6144] Debug Create/Edit Maintain Assignment

---

talentmap_api/fsbid/services/employee.py

[TM-6137](https://metaphase.atlassian.net/browse/TM-6137)
[TM-6137]: https://metaphase.atlassian.net/browse/TM-6137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Going to test in dev1 to make sure the role is properly mapped. confirmed it is

TM-6137 Org roles to post

---

talentmap_api/fsbid/services/bid_audit.py
talentmap_api/fsbid/urls/bid_audit.py
talentmap_api/fsbid/views/bid_audit.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2994)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/477)
[Ticket](https://metaphase.atlassian.net/browse/TM-6048)

TM-6048, Run Bid Audit

---

talentmap_api/fsbid/services/assignment_history.py
talentmap_api/fsbid/views/assignment_history.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/3001)
[TM-6144](https://metaphase.atlassian.net/browse/TM-6144)
[TM-6144]: https://metaphase.atlassian.net/browse/TM-6144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TM-6144] Maintain Assignment Post Hotfix

---

talentmap_api/fsbid/services/post_access.py

Reverts MetaPhase-Consulting/State-TalentMAP-API#1008

Revert "TM-6164, use display name for org, works around known FSBID issue"

---

talentmap_api/fsbid/services/bid_audit.py

use function in common file

---

talentmap_api/fsbid/views/bidding_tool.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2856)
[TM-5572](https://metaphase.atlassian.net/browse/TM-5572)
[TM-5572]: https://metaphase.atlassian.net/browse/TM-5572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TM-5572] Bidding Tool Integration (Edit)

---

talentmap_api/fsbid/services/assignment_history.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/3019)

Maintain Assignment Edit Hotfix

---

talentmap_api/common/common_helpers.py
talentmap_api/fsbid/services/client.py

[[ticket](https://metaphase.atlassian.net/browse/TM-5970)]
New - [clients_2024_07_02_125901.csv](https://github.com/user-attachments/files/16068627/clients_2024_07_02_125901.csv)

TM-5970-Client-Profile-Export

---

talentmap_api/fsbid/filters.py
talentmap_api/fsbid/services/available_positions.py

Dual Merge: 
[Ticket](https://metaphase.atlassian.net/browse/TM-6302)

TM-6302 add search flag for Critical Need

---

TM_Version.txt

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/3028)

Release 13.0

---

talentmap_api/fsbid/services/notifications.py
talentmap_api/fsbid/urls/notifications.py
talentmap_api/fsbid/views/notifications.py
talentmap_api/urls.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/3036)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/489)
[TM-6170](https://metaphase.atlassian.net/browse/TM-6170)
[TM-6170]: https://metaphase.atlassian.net/browse/TM-6170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TM-6170] TM1 Notifications (Read Only)

---

talentmap_api/fsbid/views/position_classifications.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/3058)

PPos Position Classifications: Restrict Edit to Superuser

---

talentmap_api/fsbid/services/notifications.py
talentmap_api/fsbid/urls/notifications.py
talentmap_api/fsbid/views/notifications.py

Dual Merge: 
[TM-4911](https://metaphase.atlassian.net/browse/TM-4911)
[TM-4911]: https://metaphase.atlassian.net/browse/TM-4911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TM-4911] TM1 Notifications (Edit Endpoints)

---

talentmap_api/fsbid/services/bid_audit.py
talentmap_api/fsbid/urls/bid_audit.py
talentmap_api/fsbid/views/bid_audit.py

Dual Merge: 
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/500)
[Ticket](https://metaphase.atlassian.net/browse/TM-5920)

TM-5920, Bid Audit Data, API

---

talentmap_api/fsbid/services/publishable_positions.py

[Ticket](https://metaphase.atlassian.net/browse/TM-6366)

TM-6366-Pub-Pos-Skills

---

talentmap_api/fsbid/services/bid_audit.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/3067)
[Ticket](https://metaphase.atlassian.net/browse/TM-5919)
Had to reformat the data to make the table on the Ui work

TM-5919, Bid Book Ui

---

talentmap_api/fsbid/services/panel.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/3074)
[Ticket](https://metaphase.atlassian.net/browse/TM-6408)
just had to change the name of a variable in the panel remark mapping

Tm 6410 update panel remark mapping

---

talentmap_api/fsbid/services/publishable_positions.py

😺
Dual Merge: 
- [MOCK PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/502)
[Ticket](https://metaphase.atlassian.net/browse/TM-6365)
Updated API for standardization.
WS updated GET /api/v1/backoffice/BackOfficeCRUD to return new info

TM-6365 add long desc and code to bureau filter

---

talentmap_api/common/common_helpers.py
talentmap_api/fsbid/services/client.py

https://github.com/MetaPhase-Consulting/State-TalentMAP-API/pull/1026/files

HOTFIX, employee profile export

---

talentmap_api/fsbid/services/admin_projected_vacancies.py

Dual Merge: 
[Ticket](https://metaphase.atlassian.net/browse/TM-6371)

[TM-6371] Publishable Positions and Projected Vacancies Timestamps

---

talentmap_api/fsbid/services/notifications.py
talentmap_api/fsbid/urls/notifications.py
talentmap_api/fsbid/views/notifications.py

Dual Merge: 
[Ticket](https://metaphase.atlassian.net/browse/TM-6229)

[TM-6229] TM1 Notification Send Cable

---

talentmap_api/fsbid/services/client.py
talentmap_api/fsbid/services/remark.py
talentmap_api/fsbid/views/client.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/3077)
[Ticket](https://metaphase.atlassian.net/browse/TM-4844)

TM-4844-CDO-API

---

TM_Version.txt
talentmap_api/fsbid/services/client.py

[Ticket](https://metaphase.atlassian.net/browse/TM-6425)
Added some None checks that caused the api call to break

Tm 6425 export button not working when exporting client list

---

talentmap_api/fsbid/services/assignment_cycles.py
talentmap_api/fsbid/services/bid_audit.py
talentmap_api/fsbid/urls/bid_audit.py
talentmap_api/fsbid/views/bid_audit.py

Dual Merge: 
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/507)
[Ticket](https://metaphase.atlassian.net/browse/TM-6147)

TM-6147, Bid Book MDS

---

talentmap_api/fsbid/services/bid_audit.py

few things i noticed when testing - non deal breakers but worth fixing

cleanup, touchups

---

TM_Version.txt
talentmap_api/fsbid/services/client.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/3087)
[Ticket](https://metaphase.atlassian.net/browse/TM-6425)
Updated version
Added error handling for client export

Tm 6425 export button not working api

---

talentmap_api/fsbid/services/available_positions.py
talentmap_api/fsbid/services/projected_vacancies.py

Reverts MetaPhase-Consulting/State-TalentMAP-API#1071
Failed in dev1

Revert "TM-6348-DETO-RWA-Bidder-Position-Searches-Integration"

---

talentmap_api/fsbid/services/agenda.py
talentmap_api/fsbid/services/agenda_employees.py
talentmap_api/fsbid/services/common.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/3096)
[Ticket](https://metaphase.atlassian.net/browse/TM-6433)
Added ability to filter by pmipmseqnum

Tm 6433 re work panel meeting agendas page

---

talentmap_api/fsbid/services/available_positions.py
talentmap_api/fsbid/services/projected_vacancies.py

https://metaphase.atlassian.net/browse/TM-6521
endpoints used:
Endpoint post /api/v2/futureVacancies
Params:
{
"page_size": 1,
"page_index": 1,
"pv_elig_tele_ind": "Y"|| "N"
}
Response should contain : "avail_telework_pos": "Y" || "N",
Endpoint: post /api/v2/cyclePositions
Params
{
"page_size": 1,
"page_index": 1,
}
Payload should contain : "avail_telework_pos": "Y" || "N",

RWA/DETO Filtering API

---

talentmap_api/fsbid/services/client.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/3115)
[Ticket](https://metaphase.atlassian.net/browse/TM-6581)

TM-6581-API-Email-Comments

---

talentmap_api/common/management/commands/create_base_permissions.py
talentmap_api/fsbid/services/employee.py
talentmap_api/fsbid/views/employee.py
talentmap_api/user_profile/management/commands/create_seeded_users.py

[[Ticket](https://metaphase.atlassian.net/jira/software/c/projects/TM/boards/1?assignee=712020%3A3d9639a5-439c-4e2d-9bce-37b6924384d2&selectedIssue=TM-6490)]
Adding the EL_CDO role to this project. This role was added in the ROLE_MAPPING dictionary (fsbid/services/employee.py)

Adding el_cdo role

---

talentmap_api/fsbid/views/positions.py

Dual Merge: 
[Ticket][(linkToTicket)](https://metaphase.atlassian.net/jira/software/c/projects/TM/boards/1?assignee=712020%3A3d9639a5-439c-4e2d-9bce-37b6924384d2&selectedIssue=TM-6490)
Adding the el_cdo and fsbid_admin roles for this application.

Tm 2120 export el positions table

---

talentmap_api/fsbid/services/client.py
talentmap_api/fsbid/urls/client.py
talentmap_api/fsbid/views/client.py

Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/3124)
[Ticket](https://metaphase.atlassian.net/browse/TM-6403)
https://github.com/user-attachments/assets/8e74bb33-7a89-4448-afb8-6b8c0c79cfe0

TM-6403-CDO-Table-API

---

talentmap_api/fsbid/services/notifications.py
talentmap_api/fsbid/urls/notifications.py
talentmap_api/fsbid/views/notifications.py

Changes:
- Renamed functions for understandability
- Updated comments
- Corrected OPS endpoints' parameters and REST compliancy
Dual Merge: 
- [FE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/3123)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/512)
[Ticket](https://metaphase.atlassian.net/browse/TM-6614)

[TM-6614] TM1 OPS Endpoints

---

talentmap_api/fsbid/services/agenda.py

[Ticket](https://metaphase.atlassian.net/browse/TM-6739)
updated skill filter, to reflect changes with WS

update skill filter
